    SELECT 
    U.CODUSU || ' - ' || U.NOMEUSU AS NOME,
    U.AD_CODEMPLOT || ' - ' || E.NOMEFANTASIA AS EMPRESA,
    U.CODPARC || ' - ' || P.NOMEPARC AS PARCEIRO,
    NVL(TIM_FORMATATELEFONE(P.TELEFONE),'Sem telefone') AS TELEFONE
    FROM TSIUSU U
    LEFT JOIN TSIEMP E ON E.CODEMP = U.AD_CODEMPLOT
    LEFT JOIN TGFPAR P ON P.CODPARC = U.CODPARC
    WHERE NVL(DTLIMACESSO,SYSDATE - 1) >= SYSDATE
    AND U.CODGRUPO = 4
    ORDER BY U.AD_CODEMPLOT ASC
